# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Hossamelden Elmalah
# SPDX-License-Identifier: Apache-2.0
"""Shared classification taxonomy translations (German -> English).

This module is the single source of truth for the OEKOBAUDAT 4-level
classification taxonomy used by:
  - the Ökobaudat Connector pushbutton's Materials Classification filter
    chips (window.py imports _DE_TO_EN_LABELS from here)
  - the Validation pushbutton's results table and exports (translates
    classification paths to English when the user selects EN)
  - search_helpers.build_searchable (translates the haystack so English
    queries match English category words when EN is selected)

Pure data + one helper function. No WPF, no Revit, no pyrevit imports -
safe to import from IronPython 2.7 (in-Revit) and CPython 3 (offline
benchmark tools).
"""

_DE_TO_EN_LABELS = {
    # ── L1 roots (11) ──────────────────────────────────────────────
    u'Mineralische Baustoffe':                         u'Mineral Construction',
    u'Holz':                                           u'Wood',
    u'Metalle':                                        u'Metals',
    u'Kunststoffe':                                    u'Plastics',
    u'Dämmstoffe':                                     u'Insulation',
    u'Beschichtungen':                                 u'Coatings',
    u'Komponenten von Fenstern und Vorhangfassaden':   u'Windows & Façades',
    u'Gebäudetechnik':                                 u'Building Services',
    u'Komposite':                                      u'Composites',
    u'Sonstige':                                       u'Other',
    u'End of Life':                                    u'End of Life',
    # ── L2 subgroups ──────────────────────────────────────────────
    # Mineralische Baustoffe
    u'Asphalt':                                        u'Asphalt',
    u'Bindemittel':                                    u'Binders',
    u'Mörtel und Beton':                               u'Mortar & Concrete',
    u'Pigmente':                                       u'Pigments',
    u'Steine und Elemente':                            u'Stones & Elements',
    u'Zuschläge':                                      u'Aggregates',
    # Holz
    u'Holzböden':                                      u'Wood Flooring',
    u'Holzwerkstoffe':                                 u'Engineered Wood',
    u'Modifiziertes Holz':                             u'Modified Wood',
    u'Vollholz':                                       u'Solid Wood',
    # Metalle
    u'Aluminium':                                      u'Aluminium',
    u'Blei':                                           u'Lead',
    u'Edelstahl':                                      u'Stainless Steel',
    u'Kupfer':                                         u'Copper',
    u'Oberflächenbehandlung und Beschichtung von Metallen': u'Surface Treatment',
    u'Stahl und Eisen':                                u'Steel & Iron',
    u'Zink':                                           u'Zinc',
    # Kunststoffe
    u'Bodenbeläge':                                    u'Floor Coverings',
    u'Dachbahnen':                                     u'Roofing Membranes',
    u'Dichtmassen':                                    u'Sealants',
    u'Folien und Vliese':                              u'Films & Nonwovens',
    u'Kunststoffprofile elastisch':                    u'Elastic Profiles',
    u'Profile':                                        u'Profiles',
    u'Rohre':                                          u'Pipes',
    # Dämmstoffe
    u'Baumwolle':                                      u'Cotton',
    u'Blähperlit':                                     u'Expanded Perlite',
    u'Calciumsilikat':                                 u'Calcium Silicate',
    u'Dämmelemente':                                   u'Insulation Elements',
    u'Expandierter Kork':                              u'Expanded Cork',
    u'Expandiertes Polystyrol (EPS)':                  u'EPS',
    u'Extrudiertes Polystyrol (XPS)':                  u'XPS',
    u'Flachsfaser':                                    u'Flax Fibre',
    u'Hanffaser':                                      u'Hemp Fibre',
    u'Harnstoff-Formaldehydharz':                      u'Urea-Formaldehyde',
    u'Holzfasern':                                     u'Wood Fibres',
    u'Holzwolleplatten':                               u'Wood-Wool Boards',
    u'Kautschuk':                                      u'Rubber',
    u'Melaminharz':                                    u'Melamine',
    u'Mineralwolle':                                   u'Mineral Wool',
    u'Ortschaum':                                      u'In-situ Foam',
    u'Phenolharz-Hartschaum (PF)':                     u'PF Rigid Foam',
    u'Polyethylen':                                    u'Polyethylene',
    u'Polyurethan-Hartschaum (PU)':                    u'PU Rigid Foam',
    u'Schafswolle':                                    u'Sheep Wool',
    u'Schaumbeton':                                    u'Foamed Concrete',
    u'Schaumglas':                                     u'Foam Glass',
    u'Siliziumdioxid-basiert':                         u'Silica-Based',
    u'Stroh':                                          u'Straw',
    u'Wärmedämmverbundsystem':                         u'ETICS',
    u'Zellulosefaser':                                 u'Cellulose Fibre',
    # Beschichtungen
    u'Bituminöse Anstriche':                           u'Bituminous Coatings',
    u'Brandschutz':                                    u'Fire Protection',
    u'Fassadenfarben':                                 u'Façade Paints',
    u'Grundierungen':                                  u'Primers',
    u'Innenbeschichtungen':                            u'Interior Coatings',
    u'Lacke und Lasuren':                              u'Lacquers & Stains',
    u'Reaktionsharze':                                 u'Reactive Resins',
    # Komponenten von Fenstern und Vorhangfassaden
    u'Antriebssysteme':                                u'Drive Systems',
    u'Beschläge':                                      u'Fittings',
    u'Dichtungskomponenten / -materialien':            u'Sealing Components',
    u'Fassaden':                                       u'Façades',
    u'Fenster':                                        u'Windows',
    u'Füllungen':                                      u'Infill Panels',
    u'Rahmen':                                         u'Frames',
    u'Tageslichtsysteme und Rauch- / Wärmeabzugsanlagen': u'Daylight & Smoke Vents',
    u'Türen und Tore':                                 u'Doors & Gates',
    u'Zubehör für Fenster, Fassaden, Türen und Tore':  u'Accessories',
    # Gebäudetechnik
    u'Beförderung':                                    u'Vertical Transport',
    u'Elektro':                                        u'Electrical',
    u'Heizung':                                        u'Heating',
    u'Klimatisierung und Lüftung':                     u'HVAC',
    u'Nutzung':                                        u'Use-Phase Energy',
    u'Sanitär':                                        u'Sanitary',
    # Komposite
    u'Systembauteile':                                 u'System Components',
    # Sonstige
    u'Baustellenprozesse':                             u'Construction Site',
    u'Energieträger - Bereitstellung frei Verbraucher': u'Energy Carriers',
    u'Güter - Transporte[t km]':                       u'Freight Transport',
    u'Personen - Transporte[Personen km]':             u'Passenger Transport',
    # End of Life
    u'Generisch':                                      u'Generic',
    # ── L3 / L4 leaves (auto-derived from cached classification paths) ─
    # Mineralische Baustoffe / Asphalt
    u'Asphaltbinder':                                  u'Asphalt binder',
    u'Gussassphalt':                                   u'Mastic asphalt',
    u'Splittmastixasphalt':                            u'Stone mastic asphalt',
    u'Tragschichten':                                  u'Base courses',
    # Mineralische Baustoffe / Bindemittel
    u'Gips':                                           u'Gypsum',
    u'Kalk':                                           u'Lime',
    u'Lehm':                                           u'Clay (loam)',
    u'Zement':                                         u'Cement',
    # Mineralische Baustoffe / Mörtel und Beton
    u'Beton':                                          u'Concrete',
    u'Betonzusatzmittel':                              u'Concrete admixtures',
    u'Estrich trocken':                                u'Screed (dry)',
    u'Kleber und Klebemörtel':                         u'Adhesives & adhesive mortars',
    u'Mauermörtel':                                    u'Masonry mortar',
    u'Putz und Putzmörtel':                            u'Plaster & plaster mortar',
    # Mineralische Baustoffe / Pigmente
    u'Anorganische Pigmente':                          u'Inorganic pigments',
    # Mineralische Baustoffe / Steine und Elemente
    u'Betonfertigteile und Betonwaren':                u'Precast concrete & goods',
    u'Brandschutzplatten':                             u'Fire-protection boards',
    u'Dachsteine':                                     u'Roof tiles (concrete)',
    u'Dachziegel':                                     u'Roof tiles (clay)',
    u'Deckenplatten':                                  u'Ceiling panels',
    u'Faserzement':                                    u'Fiber cement',
    u'Fliesen und Platten':                            u'Tiles & slabs',
    u'Gipsplatten':                                    u'Gypsum boards',
    u'Glasbausteine':                                  u'Glass blocks',
    u'Hanfsteine':                                     u'Hemp-lime blocks',
    u'Kalksandstein':                                  u'Sand-lime brick',
    u'Kunststein':                                     u'Artificial stone',
    u'Lehmplatten':                                    u'Clay panels',
    u'Lehmsteine':                                     u'Clay blocks',
    u'Leichtbeton':                                    u'Lightweight concrete',
    u'Naturwerkstein':                                 u'Natural dimension stone',
    u'Porenbeton':                                     u'Aerated concrete',
    u'Schiefer':                                       u'Slate',
    u'Steinzeug':                                      u'Stoneware',
    u'Substrate':                                      u'Substrates (green roof)',
    u'Trockenestrich':                                 u'Dry screed',
    u'Ziegel':                                         u'Bricks (clay)',
    # Mineralische Baustoffe / Zuschläge
    u'Bims':                                           u'Pumice',
    u'Blähglas':                                       u'Expanded glass',
    u'Blähschiefer':                                   u'Expanded slate',
    u'Blähton':                                        u'Expanded clay',
    u'Kraftwerksnebenprodukte':                        u'Power-plant by-products',
    u'Naturstein':                                     u'Natural stone (aggregate)',
    u'Perlite':                                        u'Perlite',
    u'Sand und Kies':                                  u'Sand & gravel',
    u'Trockenschüttung':                               u'Dry fill (loose)',
    # Holz / Holzböden
    u'Kork':                                           u'Cork',
    u'Laminat':                                        u'Laminate',
    u'Mehrschichtig modulare Bodenbeläge':             u'Multilayer modular floor coverings',
    u'Parkett':                                        u'Parquet',
    # Holz / Holzwerkstoffe
    u'3- und 5-Schichtplatten':                        u'3- & 5-layer panels',
    u'Elemente aus Holzwerkstoffen':                   u'Wood-based elements',
    u'Funierschichtholz':                              u'Veneer plywood',
    u'Holzfaserplatten':                               u'Wood fibreboard (MDF/HDF)',
    u'Holzzementplatten':                              u'Wood-cement boards',
    u'Laminated Veneer Lumber (LVL)':                  u'LVL',
    u'OSB-Platte':                                     u'OSB board',
    u'Spanplatten':                                    u'Particleboard',
    u'Sperrholz':                                      u'Plywood',
    u'Wood-Plastic-Composites':                        u'WPC',
    # Holz / Modifiziertes Holz
    u'Acetyliertes Holz':                              u'Acetylated wood',
    u'Thermisch behandeltes Holz':                     u'Thermally modified wood',
    # Holz / Vollholz
    u'Balkenschichtholz (Duo-Triobalken)':             u'Duo/Trio glulam beams',
    u'Bau-Schnittholz':                                u'Construction sawn timber',
    u'Brettschichtholz (BSH)':                         u'Glulam (BSH)',
    u'Brettschichtholzplatte':                         u'CLT panel',
    u'Konstruktionsvollholz':                          u'Structural solid timber (KVH)',
    # Metalle leaves
    u'Aluminiumbleche':                                u'Aluminium sheets',
    u'Aluminiumfolie':                                 u'Aluminium foil',
    u'Aluminiumprofil':                                u'Aluminium profile',
    u'Gussteile aus Aluminium':                        u'Aluminium cast parts',
    u'Bleibleche':                                     u'Lead sheets',
    u'Befestigungsmittel':                             u'Fasteners',
    u'Edelstahl Trinkwasserrohre':                     u'Stainless-steel water pipes',
    u'Edelstahlbleche':                                u'Stainless-steel sheets',
    u'Edelstahlprofile':                               u'Stainless-steel profiles',
    u'Kupferbleche':                                   u'Copper sheets',
    u'Kupferrohre':                                    u'Copper pipes',
    u'Schmiede- und Gussteile aus Kupfer und Messing': u'Forged & cast copper/brass parts',
    u'(Nass-) Lackieren von Metallen':                 u'Wet lacquering of metals',
    u'Anodisieren von Aluminium':                      u'Anodising of aluminium',
    u'Pulverbeschichten':                              u'Powder coating',
    u'Betonstabstahl':                                 u'Reinforcing steel bars (rebar)',
    u'Betonstahlmatten':                               u'Reinforcing steel mesh',
    u'Guss- und Schmiedeteile aus Stahl und Eisen':    u'Cast & forged steel/iron parts',
    u'Stahlbleche':                                    u'Steel sheets',
    u'Stahlprofile':                                   u'Steel profiles',
    u'Zinkbleche':                                     u'Zinc sheets',
    # Kunststoffe leaves
    u'Gummi-/Kautschuk-Bodenbeläge':                   u'Rubber floor coverings',
    u'Linoleum-Bodenbeläge':                           u'Linoleum floor coverings',
    u'PVC-Bodenbeläge':                                u'PVC floor coverings',
    u'Synth. Thermoplast':                             u'Synthetic thermoplastic',
    u'Polyolefin':                                     u'Polyolefin',
    u'Textile Bodenbeläge':                            u'Textile floor coverings',
    u'Bitumen-Dachbahnen':                             u'Bitumen membranes',
    u'ECB-Dachbahnen (Ethylen-Copolymer-Bitumen)':     u'ECB membranes',
    u'EVA-Dachbahnen (Etylen-Vinylacetat)':            u'EVA membranes',
    u'Elastomer-Dachbahnen':                           u'Elastomer (EPDM) membranes',
    u'PIB-Dachbahnen (Polyisobutylen)':                u'PIB membranes',
    u'PVC-Dachbahnen':                                 u'PVC membranes',
    u'TPO-Dachbahnen (FPO)':                           u'TPO/FPO membranes',
    u'Acrylat':                                        u'Acrylic',
    u'Bitumen':                                        u'Bitumen',
    u'PUR':                                            u'PUR',
    u'PVC':                                            u'PVC',
    u'Polysulfid':                                     u'Polysulfide',
    u'Silikon':                                        u'Silicone',
    u'Baupappen':                                      u'Building cardboard',
    u'Dampfbremse':                                    u'Vapour retarder',
    u'Dampfsperre':                                    u'Vapour barrier',
    u'Folien zur Abdichtung':                          u'Waterproofing films',
    u'Technische Textilien':                           u'Technical textiles',
    u'Unterspannbahn':                                 u'Roofing underlay',
    u'Vliese':                                         u'Nonwoven fabrics',
    u'Harz-Komposit Fassadenplatten':                  u'Resin-composite façade panels',
    u'Transparente Platten':                           u'Transparent panels',
    u'Kunststoffprofile hart':                         u'Rigid plastic profiles',
    u'Abwasserrohre':                                  u'Wastewater pipes',
    u'Regen-/Grauwasserrohre':                         u'Rain/greywater pipes',
    u'Trinkwasserrohre':                               u'Drinking-water pipes',
    # Dämmstoffe leaves
    u'Baumwolle konventionell':                        u'Cotton (conventional)',
    u'Baumwolle ökologisch':                           u'Cotton (ecological)',
    u'Platten':                                        u'Boards',
    u'Calcium-Silikathydrat':                          u'Calcium silicate hydrate',
    u'Isokörbe':                                       u'Thermal-break baskets',
    u'Tragende Wärmedämmelemente':                     u'Load-bearing thermal-insulation elements',
    u'EPS grau':                                       u'EPS grey',
    u'EPS grau-weiß':                                  u'EPS grey-white',
    u'EPS weiß':                                       u'EPS white',
    u'XPS weiß':                                       u'XPS white',
    u'Vlies':                                          u'Nonwoven',
    u'Hanfdämmmatten':                                 u'Hemp insulation mats',
    u'Holzfaserdämmplatte':                            u'Wood-fibre insulation board',
    u'Holzfasern und Holzspäne, lose':                 u'Wood fibres & chips, loose',
    u'Holzwolleleichtbauplatten':                      u'Wood-wool lightweight boards',
    u'Schaum':                                         u'Foam',
    u'Glaswolle':                                      u'Glass wool',
    u'Steinwolle':                                     u'Rock wool',
    u'Mineralisch':                                    u'Mineral',
    u'PF-Platten':                                     u'PF boards',
    u'PIR-Hartschaum':                                 u'PIR rigid foam',
    u'PU Blockschaum':                                 u'PU block foam',
    u'PU mit Aluminium':                               u'PU with aluminium',
    u'PU mit Mineralvlies':                            u'PU with mineral fleece',
    u'Schafwolldämmmatten':                            u'Sheep-wool insulation mats',
    u'Schaumbeton Dämmplatten':                        u'Foamed-concrete insulation boards',
    u'Granulat':                                       u'Granulate',
    u'Hydrophobe Platten':                             u'Hydrophobic boards',
    u'Vakuumisolationspaneele':                        u'Vacuum insulation panels (VIP)',
    u'Strohballen':                                    u'Straw bales',
    u'Strohfasern':                                    u'Straw fibres',
    u'Strohplatten':                                   u'Straw boards',
    u'WDVS komplett':                                  u'ETICS complete',
    u'WDVS-Dübel':                                     u'ETICS dowels',
    u'Zellulose-Einblas-Dämmstoff':                    u'Blow-in cellulose',
    u'Zelluloseplatten':                               u'Cellulose boards',
    # Beschichtungen leaves
    u'Bitumenbeschichtungen':                          u'Bitumen coatings',
    u'Innen- und Außenbeschichtungen':                 u'Interior & exterior coatings',
    u'Dispersion':                                     u'Dispersion paint',
    u'Silikat-Dispersion':                             u'Silicate-dispersion paint',
    u'Silikonharz':                                    u'Silicone-resin paint',
    u'Grundierungen Farben und Putze':                 u'Primers (paints & plasters)',
    u'Dispersionsklebstoffe':                          u'Dispersion adhesives',
    u'Innenfarben':                                    u'Interior paints',
    u'Wand- und Deckenbeläge':                         u'Wall- & ceiling-coverings',
    u'Lacksysteme Holzfassade':                        u'Lacquer (wood façade)',
    u'Lacksysteme Holzfenster':                        u'Lacquer (wood windows)',
    u'Lacksysteme Metall':                             u'Lacquer (metal)',
    u'Parkettlack':                                    u'Parquet lacquer',
    u'Reaktionsharze auf Epoxidharzbasis':             u'Epoxy resins',
    u'Reaktionsharze auf Methacrylatbasis':            u'Methacrylate resins',
    u'Reaktionsharze auf PU-Basis':                    u'PU resins',
    # Komponenten von Fenstern und Vorhangfassaden leaves
    u'elektrisch':                                     u'Electric',
    u'mechanisch':                                     u'Mechanical',
    u'Aluminiumbeschläge':                             u'Aluminium fittings',
    u'Befestigungen':                                  u'Fastenings',
    u'Edelstahlbeschläge':                             u'Stainless-steel fittings',
    u'Fenstergriffe':                                  u'Window handles',
    u'Kunststoffbeschläge':                            u'Plastic fittings',
    u'Messingbeschläge':                               u'Brass fittings',
    u'Stahlbeschläge':                                 u'Steel fittings',
    u'Zinkbeschläge':                                  u'Zinc fittings',
    u'Dichtprofile':                                   u'Seal profiles',
    u'Elastomer-Fugenbänder':                          u'Elastomer joint tapes',
    u'Fugendichtungsbänder':                           u'Joint-sealing tapes',
    u'Sonstige Fassaden':                              u'Other façades',
    u'Vorhangfassade - Element-Fassaden':              u'Curtain wall — unitised',
    u'Vorhangfassade - Pfosten-Riegel-Fassaden':       u'Curtain wall — stick (mullion-transom)',
    u'Holz-Metallfenster':                             u'Wood-metal windows',
    u'Holzfenster':                                    u'Wood windows',
    u'Kunststofffenster':                              u'Plastic (PVC) windows',
    u'Metallfenster':                                  u'Metal windows',
    u'Sonstige Fenster':                               u'Other windows',
    u'Opake Füllungen':                                u'Opaque infill panels',
    u'Transparente Füllungen':                         u'Transparent infill panels',
    u'Aluminium thermisch getrennt':                   u'Aluminium thermally broken',
    u'Stahl':                                          u'Steel',
    u'Oberlichter':                                    u'Skylights',
    u'Rauch-/Wärmeabzugsanlagen':                      u'Smoke/heat extraction systems',
    u'Kunststoff':                                     u'Plastic',
    u'Feuer-/Rauchschutzsysteme':                      u'Fire/smoke-protection systems',
    u'Fingerschutzsysteme':                            u'Finger-protection systems',
    u'Sonnenschutzsysteme':                            u'Solar-shading systems',
    # Gebäudetechnik leaves
    u'Fahrstuhl':                                      u'Elevator',
    u'Fahrtreppe':                                     u'Escalator',
    u'Schutzsysteme zur Kabel- und Rohrabschottung':   u'Cable & pipe sealing systems',
    u'Batteriespeicher':                               u'Battery storage',
    u'Beleuchtung':                                    u'Lighting',
    u'Kabel':                                          u'Cables',
    u'Schalter und Steckdosen':                        u'Switches & sockets',
    u'Sicherungs- und Schaltschränke':                 u'Fuse & switch cabinets',
    u'Speicher':                                       u'Storage tanks',
    u'Wärmeerzeuger':                                  u'Heat generators',
    u'Wärmeverteilung und Abgabe':                     u'Heat distribution & emission',
    u'Klimatisierung/Kältemaschinen':                  u'Air conditioning / chillers',
    u'Kältemittel':                                    u'Refrigerants',
    u'Lüftungsanlagen':                                u'Ventilation systems',
    u'Zubehör':                                        u'Accessories',
    u'Nutzung Beförderungstechnik':                    u'Use: vertical transport',
    u'Nutzung Beleuchtung':                            u'Use: lighting',
    u'Nutzung Lüftung und Klimatechnik':               u'Use: ventilation & HVAC',
    u'Nutzung Wärmeerzeuger':                          u'Use: heat generators',
    u'Nutzung Wärmeerzeuger (EnEV)':                   u'Use: heat generators (EnEV)',
    u'Armaturen':                                      u'Fittings (taps, valves)',
    u'Dusch- und Badewannen':                          u'Showers & bathtubs',
    u'Sanitärkeramik':                                 u'Sanitary ceramics',
    # Komposite leaves
    u'Aussenwände':                                    u'External walls',
    u'Bewehrung':                                      u'Reinforcement',
    u'Böden':                                          u'Floor assemblies',
    u'Dachaufbauten':                                  u'Roof build-ups',
    u'Decken':                                         u'Ceiling/slab assemblies',
    u'Innenwände':                                     u'Internal-wall assemblies',
    # Sonstige leaves
    u'Bagger/Aushub':                                  u'Excavator / earthworks',
    u'Betonieren':                                     u'Concreting',
    u'Biogas':                                         u'Biogas',
    u'Erdgas':                                         u'Natural gas',
    u'Fernwärme':                                      u'District heating',
    u'Flüssiggas':                                     u'LPG',
    u'Heizöl':                                         u'Heating oil',
    u'Holz-Pellets':                                   u'Wood pellets',
    u'Pflanzenölkraftstoff':                           u'Vegetable-oil fuel',
    u'Strom':                                          u'Electricity',
    u'Trinkwasser':                                    u'Drinking water',
    u'Bahn':                                           u'Rail',
    u'Binnenschiff':                                   u'Inland barge',
    u'LKW':                                            u'HGV / truck',
    u'Seeschiff':                                      u'Sea ship',
    u'PKW':                                            u'Passenger car',
    # End of Life leaves
    u'Bauschutt':                                      u'Construction debris',
    u'Hausmüll':                                       u'Household waste',
}

def translate_path(path, lang):
    """Translate a '/'-separated classification path segment-by-segment.

    lang='de' (or anything other than 'en') returns the path verbatim.
    lang='en' looks each segment up in _DE_TO_EN_LABELS with German
    fallback for any unmapped segment - so newly-added OEKOBAUDAT paths
    keep working until they get a translation.

    Handles OEKOBAUDAT's known double-space typo in the separator by
    normalising whitespace around '/' before splitting.
    """
    if not path:
        return path or u""
    if lang != u"en":
        return path
    # Split on '/', strip whitespace per segment, drop empties, look up,
    # rejoin with the canonical single-space-slash-single-space separator.
    parts = [seg.strip() for seg in path.split(u"/")]
    parts = [seg for seg in parts if seg]
    return u" / ".join(_DE_TO_EN_LABELS.get(seg, seg) for seg in parts)
